### ISSUE TITLE
Alignment out in Safari

### ISSUE THREAD

**Issue by edisonchee** [idagds/gds-hive#7]
Version 9.1 (11601.5.17.1)

![alignment](https://cloud.githubusercontent.com/assets/5292034/14667153/4bd3ec7c-0710-11e6-82fb-706ce2e5f6df.jpg)

**Comment by edisonchee** [comment]
Somehow removing 
`height: 100%
` for `_-components-TopNav-HeroImage-SvgLogo-styles-logo-container-2QD43` gives the container a height instead.

**Comment by gyng** [comment]
Seems to be fixed, can't replicate in 9.1.1. Please re-open if the bug is still around.
